name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    tags: [ '*.*.*' ]
  pull_request:
    branches-ignore: []
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: chasemcdougall/chat-backend:dev
          context: "{{defaultContext}}:packages/api"
      # - name: Deploy to Render
      #   run: curl https://api.render.com/deploy/srv-cm67eqocmk4c73cuc7g0?key=RxUvnrm6gPo
